on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.30
      with:
        github_token: ${{ secrets.SECRET_GH_TOKEN }}
        goos: linux
        goarch: amd64
