name: Create Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Update Embedded Version String
        id: extract_changelog
        env:
          REF: ${{ github.ref }}
        run: |
          sed -i "s/version = \"0.0.0\"/version = \"${REF:11}\"/" Cargo.toml
          echo "version_name=${REF:10}" >> $GITHUB_OUTPUT

      - name: Install Cross-rs
        run: |
          cargo install cross --git https://github.com/cross-rs/cross

      - name: Build x86 Binary
        run: |
          cross build --release --target x86_64-unknown-linux-gnu

      - name: Build ARM Binary
        run: |
          cross build --release --target aarch64-unknown-linux-gnu

      - name: Extract Changelog
        env:
          REF: ${{ github.ref }}
        run: |
          sed -n "/^## ${REF:10}/,/^## /{/^## /b;p}" CHANGELOG.md > ./RELEASE_CHANGELOG

      - name: Create Checksum and Add to Changelog
        run: |
          mv target/x86_64-unknown-linux-gnu/release/downloader downloader_x86
          mv target/aarch64-unknown-linux-gnu/release/downloader downloader_arm
          X86_SUM=$(sha256sum downloader_x86)
          ARM_SUM=$(sha256sum downloader_arm)
          echo -e "\n#### SHA256 Checksum\n\`\`\`\n$X86_SUM\n$ARM_SUM\n\`\`\`\n" >> ./RELEASE_CHANGELOG
          echo -e "$X86_SUM" > x86_checksum.txt
          echo -e "$ARM_SUM" > arm_checksum.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.extract_changelog.outputs.version_name }}
          body_path: ./RELEASE_CHANGELOG
          draft: true
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
          files: |
            downloader_x86
            downloader_arm
            x86_checksum.txt
            arm_checksum.txt